version: '3.8'

services:
# Como não fiz com php, usei o node no docker para não precisar instalar o node na máquina
  api:
    image: node:20.17.0-alpine
    container_name: tm_api
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9000:3000" 
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: tm_db
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: