version: '3.8'

services:
  api:
    image: node:20.17.0-alpine
    container_name: tm_api
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "9000:3000"
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: tm_db
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
